os: linux
dist: jammy
language: java
jdk: openjdk17
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/graalvm"
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
addons:
  sonarcloud:
    organization: molgenis
    token:
      secure: KllHGH4ugHzXbcjNxmOdfxTflqgpYuMeFP95L2pLFn/nQq5p9CLbIiguN13Ha+J60/DAqcOG5wwMxso83B4+MVEQj+WPn/8X0Whn17oecVEABjV0h1Kw5+G7al5CtPWxL7Uv66xy/MW7mopoHMAPrm0t3S2V4vYWNprsCjKQu92dPk3L+OpyV7oZVDhrkxRvF4SsaWT65J5+z0gpsBp5rFYRIw51+aMFkSl3EUac2fVx4k6IO7P7Sw7gX0cC+3CKm2I1pdSfw1pXqPky79kByMtoJgc7ylcm8h7wOX6ZqLmC0FsG84IQ9xGnxeq9iqCV8RyHExJXQ9nPE2CM7SVJEJn4farDJmh2M1sbUNUHO7+GsQBvd33y9NLnBrJylWFq0Xnd3w0IpdBx8YVkTGSAwcB0ZA+c9QPthN5I3K/MK2iiP+JkgiB0sbO3qTM7bo3Cxkvnxilvx1J/lIaGK8db/klkv2B61zwSUOL/GP0cBv9EQTe+3gOS0Xs72YTpcCErWXIRu+QVjkGtNXPQlQKgcenl8qJRNXBGqwO3L0gjZpWp5U2oEcDbkuRx4pVuCcmNKI2/pj8t31l8INe5tC8xphEIpkqvX0rIYqUnMFcW7n4HsTnBlluafqwZCwypUIyIJAJNBwooQgOhWwKkgMEd2IxUSwMZwO7ZH849XorRSoQ=
before_install:
  - ./install-graal.sh $HOME
  - export JAVA_HOME=$HOME/graalvm/graalvm
  - export PATH=JAVA_HOME/bin:$PATH
script:
  - mvn clean install sonar:sonar -Pcoverage -Dsonar.projectKey=molgenis_vip-inheritance
deploy:
  provider: releases
  token:
    secure: cgRNWMWg6I1FAsBkkKtR5ervgVAl18TCpbEckfwSwyaqZppK16QTx06iTFv1fAoTK2/rxPMMoonlrsxj2P9BZ9yKkCzow1Icdqppbd63VqCDUWLBwEhOVNVEZtDs5LGcIvBwoyqB2uA+/PJoyZ9sRlX5I6gmlwTDkiYiknDL4Re+DQkkDUPr+c80GX+xTTMKJgSePlt4b0cq0TiRk8nqDJtPTho/CYnRvQfBpOYa91BZ0WqiIxpwnNbBEbFxHBOFOTPX04Aq3ec42BFL4QDeK37DRd9B49z2s+PKvcxj5kFO+y/r5AnuuaH8wnxYxSU1+rmLAnFYfWfGCzE2Ipf1dxBx5ixwF+fJkpyJvwe6Z/OFQV375lgUaY3bpbMyQ72JT/ZC0ATgZut2pkuOfGWupDiTqxnAtX8K/YwcQjWd9kN+Fxq6d3eSa6CiJciHkAJk4KL4FxaR+czqUWk0j3M2qAtZmkvaUPqFvka00iecEkujdfO34rg0VzXm96PY1cBV1AQUKLZAjT0o0nkHMLwKGUoIWCZTr/ow81H5sNwagUYWpc6QdjTM4m25Xn4++JvtxK+ivqbg7x60wZQKhAWJah6nvidEm3ReV/h6X8EwDGP8pzYLDpRT5IR5EbzfY/Lp6Oo2S8Ij+9gHiTA0oXhjpof7wwLZE0VahE73AHtFnI4=
  file: target/genemap-mapper.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
