arch: amd64
os: linux
dist: noble
language: minimal
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/jdk"
    - "$HOME/mvn"
branches:
  only:
    - main
    - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
  # install temurin 25
  - |
    if [ ! -f "$HOME/jdk/bin/java" ]; then
      curl --fail --silent --show-error --location --output "$HOME/jdk.tar.gz" \
        https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.2%2B10/OpenJDK25U-jdk_x64_linux_hotspot_25.0.2_10.tar.gz
      echo "987387933b64b9833846dee373b640440d3e1fd48a04804ec01a6dbf718e8ab8  $HOME/jdk.tar.gz" | sha256sum --check          
      tar --extract --gunzip --strip-components=1 --directory="$HOME/jdk" -f "$HOME/jdk.tar.gz"
      rm "$HOME/jdk.tar.gz"
    fi
  # install maven 3.9.11
  - |
    if [ ! -f "$HOME/mvn/bin/mvn" ]; then
      curl --fail --silent --show-error --location --output "$HOME/mvn.tar.gz" \
        https://archive.apache.org/dist/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz
      echo "4b7195b6a4f5c81af4c0212677a32ee8143643401bc6e1e8412e6b06ea82beac  $HOME/mvn.tar.gz" | sha256sum --check
      tar --extract --gunzip --strip-components=1 --directory="$HOME/mvn" -f "$HOME/mvn.tar.gz"
      rm "$HOME/mvn.tar.gz"
    fi
script:
  - mvn verify --batch-mode --no-transfer-progress --activate-profiles coverage -Djacoco.skip.report=true
deploy:
  provider: releases
  token:
    secure: Gh2FxnhETWAWbHAF8LYg7X55VcSmnCaf6GmAli1/nAzKCuUkAeW0WOVgEmHGXUXXV2IHj8buD3q5J5AaGwrMwVFsAtK/Gf2fZ984vDYOHeTlcFWzYbwCGrpTJizpA+R9TvQesCrX4JgvgiHShmC8ewrw011bUiEhcEfRK+5sSEHbhOwfZcOnO3Lq3iQiF83UCY3eKITaWrsTANZDf7ZAd1VqE1dQUCicjfXaVfryGl20OA9b4cQinkf3JfnTX7Nq/OMonV89+BecHdyU4fA0mXTn6Onf4waLOD6kJgyHMn/q32W8lMlZ0MRAZVwW/YBW1r8X/N9WS8Sh5u3+7VjJI/AAG+yWElsIRQ8Sq4OBkIoYQJSDT2X0SwmsQZMXnD4clm0/IBtE2I4n86Ja+g+x5g5+av823RKlUQQAxXRYhnzcG6sxfo30pu3EFeqp5X9OSsYo6KQGneWadjsumGDsFki/Pn/7AIrM/poWOZ85TSDLsWj9FL7vsGqgRzZqNK3ZA4WPDm5OQF4c/6+5zsKeVDWxE9iqENBdgFwtqqoG+t3XeXjEOwod9fGASBXA4eJxXMQ3X+HdqlyZPt5nvwlBH9Bpxbum53w/PVcgqpYKHwMr7mTK+GsKkfPl0zzMdWkYQuR8PUw7OT1drU+fM1ji+WTmbyOW8R6tXqxpNTyruUc=
  file: target/genemap-mapper.jar
  on:
    tags: true
env:
  global:
    - JAVA_HOME=$HOME/jdk
    - PATH=$HOME/jdk/bin:$HOME/mvn/bin:$PATH