os: linux
dist: jammy
language: java
jdk: openjdk21
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
script:
  - mvn clean install -Pcoverage
deploy:
  provider: releases
  token:
    secure: cgRNWMWg6I1FAsBkkKtR5ervgVAl18TCpbEckfwSwyaqZppK16QTx06iTFv1fAoTK2/rxPMMoonlrsxj2P9BZ9yKkCzow1Icdqppbd63VqCDUWLBwEhOVNVEZtDs5LGcIvBwoyqB2uA+/PJoyZ9sRlX5I6gmlwTDkiYiknDL4Re+DQkkDUPr+c80GX+xTTMKJgSePlt4b0cq0TiRk8nqDJtPTho/CYnRvQfBpOYa91BZ0WqiIxpwnNbBEbFxHBOFOTPX04Aq3ec42BFL4QDeK37DRd9B49z2s+PKvcxj5kFO+y/r5AnuuaH8wnxYxSU1+rmLAnFYfWfGCzE2Ipf1dxBx5ixwF+fJkpyJvwe6Z/OFQV375lgUaY3bpbMyQ72JT/ZC0ATgZut2pkuOfGWupDiTqxnAtX8K/YwcQjWd9kN+Fxq6d3eSa6CiJciHkAJk4KL4FxaR+czqUWk0j3M2qAtZmkvaUPqFvka00iecEkujdfO34rg0VzXm96PY1cBV1AQUKLZAjT0o0nkHMLwKGUoIWCZTr/ow81H5sNwagUYWpc6QdjTM4m25Xn4++JvtxK+ivqbg7x60wZQKhAWJah6nvidEm3ReV/h6X8EwDGP8pzYLDpRT5IR5EbzfY/Lp6Oo2S8Ij+9gHiTA0oXhjpof7wwLZE0VahE73AHtFnI4=
  file: target/genemap-mapper.jar
  prerelease: true
  on:
    tags: true
  edge: true # opt in to dpl v2
